@FiapCloudGames_HostAddress = http://localhost:5092

### Login como admin
POST http://localhost:5092/api/Security/authenticateControllers/login?username=admin&password=admin
Content-Type: application/json

{}

### Login como user
POST http://localhost:5092/api/authenticateControllers/login?username=user&password=user
Content-Type: application/json

{}

### Acessar endpoint apenas para Admin
GET http://localhost:5092/api/secure/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwianRpIjoiMmNiYjY1NTItNmE4MC00OTFhLTk0NjMtZGU2M2MxMTY3YmFmIiwiZXhwIjoxNzY1NDIzNjMzLCJpc3MiOiJTdWFBcGxpY2FjYW8ifQ.TEUgzFe47PbtU2a23lzwlsxGzjgqCDawfW6Uk1h3c_k

### Acessar endpoint acessível por qualquer usuário autenticado
GET http://localhost:5092/api/secure/user
Authorization: Bearer {{token}}

